# Generated by Django 6.0.5 on 2026-05-24 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now=True)),
                ('completed', models.BooleanField(default=False)),
                ('important', models.BooleanField(default=True)),
            ],
        ),
    ]
